services:
  server:
    build:
      context: .
    develop:
      watch:
        - path: ./
          target: /var/www/html
          action: sync
    env_file:
      - .env
    ports:
      - 9101:80